--- # loop playbook
- hosts: web
  user: nodeuser
  become: yes
  connection: ssh
  tasks:
          - name: add list of users
            user: name='{{item}}' state=present
            with_items:
                    - user1
                      user2
                      user3


