--- # variable playbook
- hosts: web
  user: nodeuser
  become: yes
  connection: ssh
  vars:
          pkgname: httpd
  tasks:
          - name: install apache
            action: yum name='{{pkgname}}' state=installed

